apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - args:
        - --appendonly
        - "yes"
        image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always
