apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: frontend-deployment
  labels:
    name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: frontend

  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: supinfosxb/frontend:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 250Mi
        args:
          - redis
          - postgres


      restartPolicy: Always
    
