apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: frontend
  name: frontend
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: frontend
  type: NodePort
