apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: frontend
  name: frontend
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    name: frontend
  type: LoadBalancer
