apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: api
  name: api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: api
  type: NodePort
